### ISSUE TITLE
[Feature Request] Skin Mirroring + URL Skin Application

### ISSUE THREAD

**Issue by R00tB33rMan** [FancyMcPlugins/FancyNpcs#10]
Skin mirroring would be a cool feature. An example of implementing this onto the plugin's existing system would be:
/npc skin Test <mirror>

In addition, maybe implementing skin URL support would be a cool feature if this is also not too challenging. Here's an example:
/npc skin Test https://google.com/skin/8hjHTD6gydyhgjd7
or just /npc skin test {URL}

**Comment by Zemux1613** [comment]
Hey @R00tB33rMan what types of url do you want to support? Currently the plugin obfuscates url calls to make the system easy to use.

**Comment by matipoirierg** [comment]
Hi quick question, is sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream() related from this patch?

**Comment by Zemux1613** [comment]
Hello @matipoirierg, all changes of this patch can be seen in [this](https://github.com/OliverSchlueter/FancyNpcs/commit/27e8170a827ec97b4b43c5ab920f8e56d1d55e39) link. HttpsURLConnectionImpl#getInputStream is not affected by this patch.

**Comment by lsyk4** [comment]
Question.
It's possible to set a Image as NPC skin?
I mean when I write
/npc skin mynpc https://i.ibb.co/8dNRmfZ/chica.png
the NPC must take the skin from the image

**Comment by OliverSchlueter** [comment]
> Question. It's possible to set a Image as NPC skin? I mean when I write /npc skin mynpc https://i.ibb.co/8dNRmfZ/chica.png the NPC must take the skin from the image

Hey, it is not possible yet (that's why the issue is still open).

**Comment by OliverSchlueter** [comment]
Now it is possible, see 09c2edd41948ac01ba16bd44318d4a1392a1f0a6
