### ISSUE TITLE
Can't change glowing color when npc's type isn't player

### ISSUE THREAD

**Issue by envizar** [FancyMcPlugins/FancyNpcs#102]
![изображение](https://github.com/FancyMcPlugins/FancyNpcs/assets/87126318/1ba43365-c983-48fb-9425-dbf91e7734a7)

**Comment by Grabsky** [comment]
Can reproduce on 1.20.4, color is updated after re-logging.

**Comment by envizar** [comment]
> Can reproduce on 1.20.4, color is updated after re-logging.

I don't think it should work only after re-logging, because with player type it works without re-logging

**Comment by envizar** [comment]
Also after relogging changing npc's glowing color work as expected even with non-player npcs

**Comment by OliverSchlueter** [comment]
Should be fixed in the latest dev build
