### ISSUE TITLE
LMB and RMB on NPC triggering different action

### ISSUE THREAD

**Issue by RealKomander** [FancyMcPlugins/FancyNpcs#104]
Basically I want to make it so that if you left click an NPC, it sends you to another server, but if you left click it, it performs a console command. Is it possible?

**Comment by OliverSchlueter** [comment]
It's not yet possible, but it's on the TODO and will be implemented soon

**Comment by OliverSchlueter** [comment]
Added in the latest version (https://fancyplugins.de/docs/fn-tutorials-new-interaction-system.html)
