### ISSUE TITLE
ProtocolLib

### ISSUE THREAD

**Issue by Zemux1613** [FancyMcPlugins/FancyNpcs#12]
Implementation of a ProtocolLib support which handles the package send. 

Why? The version differences become relatively unimportant and theoretically the support of older Minecraft versions becomes possible.

**Comment by OliverSchlueter** [comment]
The thing is, I don't really want to depend on other dependencies but I'll keep it in mind for the future

**Comment by Zemux1613** [comment]
You can implement the part optional :)

**Comment by OliverSchlueter** [comment]
I don't think I'll implement this, since the new project structure already allows support for multiple versions.
If you want to do it, feel free to, but otherwise this can be closed.
