### ISSUE TITLE
give npc ability to walk

### ISSUE THREAD

**Issue by khtpro** [FancyMcPlugins/FancyNpcs#126]
i love this PLUGIN! its a great alternative for citizen, free provides what i need but i need more features...i just want my players to experience to have their waifu in the server :D i dont want them to feel alone :( please add it a new atleast let them walk loop

**Comment by OliverSchlueter** [comment]
Walking npcs is planned to be added later this year. I already made some raw notes for the implementation and general design of the feature. There will be some sort of waypoints and you can link each waypoint with another.

**Comment by OliverSchlueter** [comment]
Duplicate of #77 #75
