### ISSUE TITLE
Fancynpc Skins doesnt support bedrock 😭😭😭

### ISSUE THREAD

**Issue by khtpro** [FancyMcPlugins/FancyNpcs#128]
![image](https://github.com/FancyMcPlugins/FancyNpcs/assets/137651996/a0e7dd13-a1f5-4af6-89b6-c8df30c9da55)

please make the plugin compatible to bedrock

**Comment by khtpro** [comment]
i did fix it,, by using skin restorer,, but if possoble hoping the plugin skin will support the bedrock on the future

**Comment by OliverSchlueter** [comment]
I'm still sceptical with bedrock support, since I personally don't like Bedrock. But some day I'll think about adding official support for it.

**Comment by OliverSchlueter** [comment]
There won't be official bedrock support. Someone can create a FancyNpcs fork with bedrock support, but I can't even start Minecraft Bedrock edition on my machine.
