### ISSUE TITLE
[Feature Request] Add toggle displayname

### ISSUE THREAD

**Issue by Aitooor** [FancyMcPlugins/FancyNpcs#13]
Add command to toggle displayname

**Comment by OliverSchlueter** [comment]
You can use "<empty>" as displayName to make the nametag invisible.
/npc displayName myNpc <empty>

**Comment by Aitooor** [comment]
> You can use "" as displayName to make the nametag invisible. /npc displayName myNpc

I do this on Folia and return the NPC id

**Comment by OliverSchlueter** [comment]
Sorry, my bad, it's "`<empty>`". I don't know why github didn't show it
