### ISSUE TITLE
Unable initialize on folia

### ISSUE THREAD

**Issue by paul0665** [FancyMcPlugins/FancyNpcs#134]
Folia version 1.20.6-DEV-master@d797082

openjdk version "21.0.3" 2024-04-16 LTS
OpenJDK Runtime Environment Zulu21.34+19-CA (build 21.0.3+9-LTS)
OpenJDK 64-Bit Server VM Zulu21.34+19-CA (build 21.0.3+9-LTS, mixed mode, sharing)

[latest.log](https://github.com/user-attachments/files/16240382/latest.log)

**Comment by OliverSchlueter** [comment]
Try to use a mojang mapped jar of Folia

**Comment by paul0665** [comment]
It work when using mojang mapped
