### ISSUE TITLE
support Kaiju? (Folia's fork)

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [FancyMcPlugins/FancyNpcs#14]
your plugin is very great, but can you let it running on Kaiju? thx very much!
https://github.com/KaiijuMC/Kaiiju

**Comment by mani1232** [comment]
Lol, folia fork, im need test it

**Comment by xiaoyueyoqwq** [comment]
> Lol, folia fork, im need test it

don't worry about it
I finish your work just now ;)
[FancyNpcs.zip](https://github.com/FancyMcPlugins/FancyNpcs/files/11469303/FancyNpcs.zip)

My friend helped me to finish it, now i get an issue about fake player will disappear in server restart
If you want, you can disscussion with him: [@MidnightTale](https://github.com/MidnightTale)

**Comment by OliverSchlueter** [comment]
Hey, could you please make a PR instead of sending the sourcecode?

**Comment by xiaoyueyoqwq** [comment]
> Hey, could you please make a PR instead of sending the sourcecode?

none, he said he only remove plugin's folia check, so i think don't need to send sourcecode

**Comment by OliverSchlueter** [comment]
Okay, I updated the feature/folia branch to load with Folia and any of it's forks
