### ISSUE TITLE
NPC Scale not changing - command does not appear 

### ISSUE THREAD

**Issue by NOIR-DexPrkr** [FancyMcPlugins/FancyNpcs#143]
I am on paper 1.20.1 using the latest version of the plugin.
When I try changing the scale of the npc it does nothing.
Try changing the scale from config file but when using /reload for the plugin the npc sometimes loses all its properties, items, skin.

Is this new or is it a common error? 
Is there a workaround? I had the plugin in a prev world and it worked great. Now I need it to make giants in my spawn.

Thanks, I hope you can help me.

**Comment by OliverSchlueter** [comment]
The scale feature is only for 1.20.6+ servers

**Comment by OliverSchlueter** [comment]
It should be added in the docs

**Comment by NOIR-DexPrkr** [comment]
> The scale feature is only for 1.20.6+ servers

I update my server to 1.20.6 and it still is not working.
Even from the config, What am i doing wrong?

**Comment by OliverSchlueter** [comment]
Fixed in the latest version
