### ISSUE TITLE
[Feature Request] NPC Message command

### ISSUE THREAD

**Issue by kixxu** [FancyMcPlugins/FancyNpcs#15]
Command will look like: /npc message {NPC} {MESSAGE} 

With this command any NPC that you choose will send custom message to player who clicked NPC. (Only for player that clicked NPC, not on global chat).

**Comment by OliverSchlueter** [comment]
I can add that 👍 
For now you could use: `/npc serverCommand <npc> tellraw {player} "your message"`

**Comment by OliverSchlueter** [comment]
Will be included in the next version

Thank you for the suggestion
