### ISSUE TITLE
Invisible Non-Player NPCs after created.

### ISSUE THREAD

**Issue by AddyPete** [FancyMcPlugins/FancyNpcs#153]
Player NPCs are fine, and can be seen after freshly created, however **on non-player NPCs, they are invisible after freshly created.** Relogging shows the non-player NPC. 

Pupur Version: 1.21 (latest)
Plugin Version: 2.2.1

**Comment by bobbyl140** [comment]
+1

**Comment by OliverSchlueter** [comment]
Yeah that's a known issue

**Comment by OliverSchlueter** [comment]
Should be fixed in the latest dev build (#207)
