### ISSUE TITLE
Scaled NPC's FancyHologram display names are at wrong height

### ISSUE THREAD

**Issue by UsainSrht** [FancyMcPlugins/FancyNpcs#169]
![image](https://github.com/user-attachments/assets/1d6bd296-8b6a-4ebf-acfb-10c2e34cb898)

fancyholograms 2.3.3
fancynpcs 2.2.2

**Comment by MiguVT** [comment]
Known issue, waiting to Oliver reply for a fix: https://github.com/FancyMcPlugins/FancyHolograms/issues/139 https://github.com/FancyMcPlugins/FancyHolograms/issues/122
