### ISSUE TITLE
NPC display name should display per-player

### ISSUE THREAD

**Issue by Lory9098** [FancyMcPlugins/FancyNpcs#172]
Hi, i'm having this problem that with '&6+&e%player_name%' display name, %player_name%, is the name of the last player joined, the placeholder is working in fact
messages:
- '&d%player_name&'

its working properly. I haven't see the code but i'm assuming that you're creating an entity in general, but you should send a packet for the entity without creating it, to avoid this thing.

**Comment by OliverSchlueter** [comment]
I'll try to reproduce.

**Comment by Lory9098** [comment]
and i have another problem, when an npc is sitting, if i try to make them turn to the player only the head moves, and not the body

**Comment by Lory9098** [comment]
i'm sorry if i'm creating some confusion, the bug is on FancyHolograms..i'll let you know later if its on FancyNPCS too

**Comment by Lory9098** [comment]
okl no only on FancyHolograms, sorry again

**Comment by Grabsky** [comment]
I can reproduce this issue on FancyNpcs 2.3.0. Placeholders are parsed locally, but refreshed globally for all players in range.
![image](https://github.com/user-attachments/assets/481c24ca-d858-421a-9dc9-ca5b4f7d0dbc)

**Comment by OliverSchlueter** [comment]
Should be fixed in the latest dev build (#206)
