### ISSUE TITLE
Copied NPCs share actions until restart

### ISSUE THREAD

**Issue by OakLoaf** [FancyMcPlugins/FancyNpcs#173]
When copying an NPC the copied NPC will then share actions with the original NPC, if you edit the actions for 1 NPC they will also edit for the other NPC too

I have only tested this with actions but I imagine equipment and other objects that are shared when copying will also replicate this behaviour

**Comment by OliverSchlueter** [comment]
Fixed in 8939302cbedfe2432bb55bc29a30309c22948fe3
