### ISSUE TITLE
NPCs not rendering. [Dev Builds]

### ISSUE THREAD

**Issue by Kruseified** [FancyMcPlugins/FancyNpcs#174]
Instance Version: 1.20.6
FancyNPC Build: 2.2.2.198 & 2.2.2.199 (issue found)

All npcs fail to load with the most recent development builds rendering them useless, this may only be a issue occurring with the 1.20.6 instance. But none the less, should be listed.

Note: Was utilizing new placeholder based skin sources, only separation of use between the two versions to my understanding. 

Have migrated to previous 2.2.2 stable builds and issue is not repeated.

**Comment by Grabsky** [comment]
Can you check if the problem still exist on 2.3.0?

**Comment by Kruseified** [comment]
Will do!

**Comment by OliverSchlueter** [comment]
Does the problem still exists?

**Comment by Kruseified** [comment]
Issue seems to be resolved.
