### ISSUE TITLE
Load skins from a local folder

### ISSUE THREAD

**Issue by ChrisTVH** [FancyMcPlugins/FancyNpcs#177]
I find it unreliable to have to rely on external services to load the skins, plus it has a bit long response time.

**Comment by OliverSchlueter** [comment]
Every single skin needs to be applied to a official minecraft account to be used. Platforms like MineSkin have many many donated minecraft accounts, where those skins are applied.

Basically the solution would be to upload the skin file to MineSkin and let them apply it to a minecraft account and then consume the skin of the account.

If we would really not depend on external services, we would need a ton of minecraft accounts, which do cost money. I personally don't want to spend hounderts of euros for that.

**Comment by Grabsky** [comment]
> @ChrisTVH: So how does citizens do that?

Citizens2 does use MineSkin API as well.
https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/util/MojangSkinGenerator.java

> @ChrisTVH: Whether or not you need a service to apply the skin to an npc?  

Yes. Client cannot read skin texture from non-Mojang URL and you need some sort of service to upload skins to Mojang API / CDN.

**Comment by ChrisTVH** [comment]
Oh, I see then I understand why that is so.
