### ISSUE TITLE
Mirror players name to displayname

### ISSUE THREAD

**Issue by crischutu07** [FancyMcPlugins/FancyNpcs#179]
Add the feature which you can set display name and mirror the names to the player name. Just like `/npc skin foobar @mirror` command but with displayname parameter (instead of `skin`).

Alternatively, I've tried this with PlaceholderAPI using `%player_name%` placeholder and run `/npc displayname foobar %player_name%`, it worked but a little buggy, if a player joined the world that the NPCs current in, it will use that joined player name instead. (Related issues in [#172](https://github.com/FancyMcPlugins/FancyNpcs/issues/172))

**Comment by OliverSchlueter** [comment]
Should be fixed in the latest dev build (#206)
