### ISSUE TITLE
Click Action via API is not beeing saved

### ISSUE THREAD

**Issue by TheBjoRedCraft** [FancyMcPlugins/FancyNpcs#181]
When you spawn a NPC with a Click Action via the API and restart the Server, the Click Action will no longer work

**Comment by TheBjoRedCraft** [comment]
FancyNpcs v2.3.0 - Minecraft Paper v1.20.6

**Comment by OliverSchlueter** [comment]
Do you mean the onClick callback?

**Comment by TheBjoRedCraft** [comment]
yeah

**Comment by OliverSchlueter** [comment]
Thats intended, you should create actions instead.
