### ISSUE TITLE
cooldown error when clicking on NPCs

### ISSUE THREAD

**Issue by emil-x** [FancyMcPlugins/FancyNpcs#184]
Since version 2.3.0+, when clicking on NPCs in Minecraft version 1.21.1, the interaction_on_cooldown error always appears.
In version 2.2.2, it works as expected, only triggering the error with frequent clicks.

**Comment by JonasDevDE** [comment]
Hey, can you send the error you get?

**Comment by Grabsky** [comment]
Can confirm this affects **FancyNpcs 2.3.1** running on **Purpur 1.21.1**. 

When there is no cooldown, error message appears once, but while cooldown is active - it is sent twice.

**Comment by OliverSchlueter** [comment]
Should be fixed in the latest dev build (#215)
