### ISSUE TITLE
[Suggestion] Add NPC shops

### ISSUE THREAD

**Issue by duranaaron** [FancyMcPlugins/FancyNpcs#187]
For starters, thanks for developing this awesome plugin. I personally really enjoy it.

Citizens has a very basic and barebones version of attaching GUI shops to NPC's. [https://wiki.citizensnpcs.co/Shops](Wiki)
Maybe incorporating something like this into FancyNpcs would be a nice addition. You could argue that this isn't really the plugin for it, but that's something up for you to decide.

Either way, thanks for considering my suggestion

**Comment by Matt-MX** [comment]
You can use something like [EconomyShopGUI](https://www.spigotmc.org/resources/economyshopgui.69927/) and use the `/shop <category>` command when a player clicks.

I gotta agree with you this isn't the sort of plugin to support it really.

**Comment by OliverSchlueter** [comment]
There are already ways to do it. It could be part of the FancyNpcs plugin, but I think a separate plugin/addon would fit better.
