### ISSUE TITLE
Npc interaction cooldown issue.

### ISSUE THREAD

**Issue by RexSAS** [FancyMcPlugins/FancyNpcs#188]
If you set an action on a npc and a cooldown for it, when the plugin or the server does a reload all the cooldown db will reset... that makes the cooldown impossible to use for a specific time.

**Comment by TheZexquex** [comment]
Then don't reload your production server?

**Comment by RexSAS** [comment]
Bruh... but if i want do add or modify something i can't because the db will reset... it's simpler changing the type of the db to make a file and use it to manage player's data.

**Comment by OliverSchlueter** [comment]
Currently the cooldown will reset when the plugin enables (server restart, or reloading the plugin).
I've seen some requests that the cooldown should persist between server restarts. I can't tell when this will be implemented tho.

**Comment by Grabsky** [comment]
Also a duplicate of https://github.com/FancyMcPlugins/FancyNpcs/issues/117
