### ISSUE TITLE
Expose NPC Eye Height through API

### ISSUE THREAD

**Issue by Sxtanna** [FancyMcPlugins/FancyNpcs#21]
Currently, the only way to get an NPCs eye height is by accessing the backing NMS Entity.

`Npc#getNpc().getEyeHeight()`

It would be nice *(also is also kinda required for FancyHolograms linking 🔜)* for the eye height or eye location to be directly exposed by the API.

ex.
`Npc#getEyeHeight`
or
`Npc#getEyeLocation`

**Comment by OliverSchlueter** [comment]
Added Npc#getEyeHeight, thank you
