### ISSUE TITLE
Wrong skin from player

### ISSUE THREAD

**Issue by Rewilon** [FancyMcPlugins/FancyNpcs#29]
**German:**
Wenn ich meinen Skin auf einen NPC(1) kopiere und danach meinen Skin ändere, um meinen neuen Skin auf einen anderen NPC(2) zu kopieren, erhält der zweite NPC(2) den alten Skin wie der erste NPC(1).
(Es funktioniert erst, wenn der Server neu gestartet wurde.)

**Anregung:**
Es wäre großartig, wenn es eine einfachere Möglichkeit gäbe, NPCs neue (benutzerdefinierte) Skins zuzuweisen.

**English:**
If I copy my skin to an NPC(1) and then change my skin to copy my new skin to another NPC(2), the second NPC(2) will get the old skin like the first NPC(1).
(It doesn't work until the server is restarted.)

**Suggestion:**
It would be great if there was an easier way to assign new (custom) skins to NPCs.

**Comment by OliverSchlueter** [comment]
Du kannst ja auch URLs benutzen als Skin.

**Comment by Rewilon** [comment]
Wie weise ich einem NPC denn eine Skin-URL zu?

**Comment by OliverSchlueter** [comment]
/npc skin (npc name) (url)

Die URL muss zu einen .png Bild führen

**Comment by Rewilon** [comment]
Prima. Werde das gleich mal testen.

**Comment by OliverSchlueter** [comment]
Hat es sich damit erledigt?
