### ISSUE TITLE
SendServer command

### ISSUE THREAD

**Issue by DormantCat** [FancyMcPlugins/FancyNpcs#31]
Please add commands for working with Proxy servers (BungeeCord / Velocity)

for example, /npc sendServer {NPC name} {Proxy-Server}

( Of course, it is possible to create similar functionality at the expense of other plugins, to do a kind of casting, but it would be much easier and more convenient to implement this function. )

```java

/**
* @p - The player to move
* @s - Server which to move to
*/
public void connect(Player p, String s) {
        ByteArrayDataOutput out = ByteStreams.newDataOutput();
        out.writeUTF("Connect");
        out.writeUTF(s);
        p.sendPluginMessage(plugin, "BungeeCord", out.toByteArray());
    }
```
This is a very simple solution that will allow you to move the player to another server.

**Comment by DormantCat** [comment]
Well, add the BungeeCord channel registration to OnEnable

the simplest function in my opinion.

```java
    @Override
    public void onEnable() {
        getServer().getMessenger().registerOutgoingPluginChannel(this, "BungeeCord");
        //Other code
    }
````

**Comment by OliverSchlueter** [comment]
You can use `/npc playerCommand (npc name) server (server name)`

The `server` command is already hardcoded into the playerCommand
