### ISSUE TITLE
NPCs disappear when changing worlds

### ISSUE THREAD

**Issue by ESpinach** [FancyMcPlugins/FancyNpcs#35]
1. Set `visibility_distance` to high value like `128`.
2. Spawn a few NPCs.
3. Teleport to another world without NPCs.
4. Teleport back to NPCs.

Some helpful info:
- Using latest (2.0.1) version from SpigotMC.
- Teleports (both) were done via Paper's `teleportAsync()` method.
- Server: `Purpur 1.20.1 (build 2035)`
- Possibly related plugins: `ProtocolLib, GrimAC, ViaVersion, ViaBackwards, TAB (by NEZNAMY), SuperVanish, LPX`

**Comment by SirKillian** [comment]
Same issue here.

**Comment by OliverSchlueter** [comment]
Do they show, when you move?

**Comment by ESpinach** [comment]
They show if you move out of visibility distance and then come back.
