### ISSUE TITLE
Can't interact with villager npcs

### ISSUE THREAD

**Issue by OliverSchlueter** [FancyMcPlugins/FancyNpcs#46]
1. /npc create test
2. /npc type test VILLAGER
3. /npc message test Test message
4. right click the 'test' npc
5. nothing happens

**Comment by OliverSchlueter** [comment]
Sadly not yet, I didn't forget it tho

**Comment by OliverSchlueter** [comment]
Fixed now (b93b80f75a2f300396d25fc01fe09dd1e01a4562), dev build #86

**Comment by RealKomander** [comment]
I can't right click wandering traders

**Comment by Grabsky** [comment]
> I can't right click wandering traders

Please open another issue and include more details like plugin and server version you're using.
