### ISSUE TITLE
npc displayname color not use

### ISSUE THREAD

**Issue by xiaocheng168** [FancyMcPlugins/FancyNpcs#48]
![image](https://github.com/FancyMcPlugins/FancyNpcs/assets/43944975/cdab655e-7d32-462b-b508-9721ad35d333)

can‘t use the color displayname

**Comment by xiaocheng168** [comment]
![image](https://github.com/FancyMcPlugins/FancyNpcs/assets/43944975/4c725211-f675-43ed-8994-c4d30e961506)
this is plugin version

**Comment by 1sythe** [comment]
Have a look at [this](https://docs.advntr.dev/minimessage/format.html)
