### ISSUE TITLE
Could not pass event PlayerUseUnknownEntityEvent to FancyNpcs

### ISSUE THREAD

**Issue by ninjaguardian** [FancyMcPlugins/FancyNpcs#55]
i keep getting errors: https://pastebin.com/L46qVKKy

and i cant update the paper version cuz im on minehut....

**Comment by OliverSchlueter** [comment]
Well the only way to fix, is to update paper. Maybe you can use a fork of paper that has a higher version of paper, if you understand what I mean

**Comment by cgw2023** [comment]
i got same error on folia 1.20.1

**Comment by OliverSchlueter** [comment]
Do you use the latest commit of folia 1.20.1?

**Comment by ninjaguardian** [comment]
Minehut updated paper but it it still giving this error.

https://pastebin.com/x7stSEF6

**Comment by OliverSchlueter** [comment]
> Minehut updated paper but it it still giving this error.
> 
> https://pastebin.com/x7stSEF6

Okay but this error has nothing todo with FancyNpcs?

**Comment by cgw2023** [comment]
> Do you use the latest commit of folia 1.20.1?

yes, folia 1.20.1 latest commit on sep 12 github 
https://github.com/PaperMC/Folia/commit/edafbcef6884cffe493e62cd71f4957708fba7ff

newer version is dev/1.20.2 which is still dev version

**Comment by OliverSchlueter** [comment]
Should be fixed with the newest Folia version
