### ISSUE TITLE
Npcs disappearing

### ISSUE THREAD

**Issue by xyfwdy** [FancyMcPlugins/FancyNpcs#60]
Npcs will not disappearing when teleport form same world now, but still happen when I teleport form another world.

FancyNpcs version 2.0.5

This server is running Folia version git-Folia-"edafbce" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: edafbce)
Error obtaining version information
Previous version: git-Folia-"372d479" (MC: 1.20.1)

**Comment by OliverSchlueter** [comment]
Should be fixed in 3d0324b7e7788183bdd0f39dbad426fa4cdfcd8b and [build 69](https://jenkins.fancyplugins.de/job/FancyNpcs/69/)

Thank you for reporting the bug
