### ISSUE TITLE
[Suggestion] Compatibility with BeautyQuest plugin

### ISSUE THREAD

**Issue by NoltoxGit** [FancyMcPlugins/FancyNpcs#65]
Hello,
It's possible to add the compatibility with a [BeautyQuest](https://github.com/SkytAsul/BeautyQuests/tree/release/1.0) plugin please ?
- The new compatibility would make it possible to choose one of FancyNPC's NPCs as the NPC for a quest.

Thank you so much !

**Comment by Textron1** [comment]
I joined the discord and made a github account just to make this suggestion.  Compatibility with Beauty Quests would be incredible.

**Comment by OliverSchlueter** [comment]
I don't have time for this atm and other features are more important rn. I'll keep the issue open tho.
