### ISSUE TITLE
[SUGGESTION] Server select feature by interact with NPC (link with Velocity/Bungeecord)

### ISSUE THREAD

**Issue by yukisnowflake** [FancyMcPlugins/FancyNpcs#67]
~~I would like to be able to send the player via Velocity/Bungeecord/Waterfall to the specified server in the NPC configuration when clicking on an NPC. Is this possible?~~ Solved by developer

~~I would also like to get away from the subject of my idea, and also make it possible to make NPC "sneak"~~ I'm stupid and didn't found this feature

~~Also I didn't find a way to hide the message about cooldown on interaction with NPC~~ #66

**Comment by OliverSchlueter** [comment]
1. You should be able to use the playerCommand: "/npc playerCommand (npc) server (serverName)"
the "server" command is hardcoded there

2. You can set the pose attribute on player npcs: "/npc attribute test pose crouching"

3. I was thinking of making this an option in the config
