### ISSUE TITLE
Skin from placeholder

### ISSUE THREAD

**Issue by TinyTank800** [FancyMcPlugins/FancyNpcs#68]
Using leaderboards like ajleaderboards you can get the name of a top player. Is it possible to add placeholder support for the skin of an npc.

Example: /fancynpcs:npc skin Baltop %ajlb_lb_statistic_player_kills_1_alltime_skin%

other info is %ajlb_lb_statistic_player_kills_1_alltime_skin% returns the player name like TinyTank800

**Comment by mccheeks** [comment]
Please do this

**Comment by erneto13** [comment]
+1

**Comment by MiguVT** [comment]
+1

**Comment by OakLoaf** [comment]
This is being worked on in: https://github.com/FancyMcPlugins/FancyNpcs/pull/152

**Comment by MiguVT** [comment]
Ok, tysm 💖

**Comment by OliverSchlueter** [comment]
You can try the latest dev build (https://modrinth.com/plugin/fancynpcs/version/2.2.2.188), which contains the skin rework.
Please take backups and do not use dev builds in production.

**Comment by OliverSchlueter** [comment]
Added in the latest version (2.3.0)
