### ISSUE TITLE
NPCs connecting to Worldguard. 

### ISSUE THREAD

**Issue by SonnenPingu** [FancyMcPlugins/FancyNpcs#69]
NPCs should be able to connect to Worldguard.
Either by direct command e.g. /Npc link Worldguard or something like that. 

Or the simpler solution would be to use the PlaceholderAPI when creating an NPC. 
[https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders] 
This would allow this to be fully realised via the placeholder %worldguard_region_owner% without having to change the code too much. 

However, as no % characters can currently be used in the "npc skin/create" command. 
It is currently not possible to realise this at all. 

There was already an issue for the skin. 
[FancyMcPlugins/FancyNpcs/issues/68]  
Would be nice if you could implement this function accordingly. 

Regards 

SunPingu

**Comment by OliverSchlueter** [comment]
You can use placeholders for skins in the latest version
