### ISSUE TITLE
NPC Disappearing After Setting Type

### ISSUE THREAD

**Issue by itisgriff** [FancyMcPlugins/FancyNpcs#73]
On the latest Dev version (#85) and have an NPC as the default player and as soon as you set the type to villager the entire NPC disappears. No errors in the console.

**Comment by itisgriff** [comment]
Also confirmed that setting it to anything other than type player does not display the entity.

**Comment by OliverSchlueter** [comment]
Which minecraft version do you use?

**Comment by itisgriff** [comment]
PurPur 1.20.4 latest

**Comment by OliverSchlueter** [comment]
I can't reproduce it :/

Try to rejoin or to walk out of the visibility distance and back.

**Comment by itisgriff** [comment]
Alright I have confirmed that this was fixed by updating to 1.20.4 latest PurPur. Although it was not working on purpur-1.20.2-2092. Just incase you get any other reports. Thanks for the help :)
