### ISSUE TITLE
NPC's are able to tab-complete

### ISSUE THREAD

**Issue by JonasDevDE** [FancyMcPlugins/FancyNpcs#78]
![image](https://github.com/FancyMcPlugins/FancyNpcs/assets/73913242/2c26b966-19fa-4970-9401-481babd5130f)

**Comment by envizar** [comment]
Same issue

**Comment by OliverSchlueter** [comment]
This only happens when pressing TAB while having nothing written yet, right?
It shouldn't appear when trying to tab complete in commands.

I was trying to fix it, but found no easy way, it might requires to modify outgoing packets, which is a bit more complicated.

**Comment by JonasDevDE** [comment]
> This only happens when pressing TAB while having nothing written yet, right? It shouldn't appear when trying to tab complete in commands.
> 
> I was trying to fix it, but found no easy way, it might requires to modify outgoing packets, which is a bit more complicated.

Thanks for working on this issue, i will take a look on it tomorrow.

**Comment by JonasDevDE** [comment]
> This only happens when pressing TAB while having nothing written yet, right? It shouldn't appear when trying to tab complete in commands.
> 
> I was trying to fix it, but found no easy way, it might requires to modify outgoing packets, which is a bit more complicated.

Hey, I just checked. The error also occurs if you have already written a message.

**Comment by OliverSchlueter** [comment]
We might found a fix for this. We're currently testing it, because it might affect other features.

**Comment by envizar** [comment]
Great!

**Comment by OliverSchlueter** [comment]
Should be fixed in [dev build 177](https://modrinth.com/plugin/fancynpcs/version/2.2.0.177). Please test it and give feedback, if every other feature still works
