### ISSUE TITLE
Can't change pose after changing pose to "sitting"

### ISSUE THREAD

**Issue by envizar** [FancyMcPlugins/FancyNpcs#82]
When i execute `/npc attribute my_npc pose sitting`, my npc's pose changes to sitting
But when I execute `/npc attribute my_npc pose standing`, my npc's pose is still sitting

Also when I execute `/npc attribute my_npc pose crouching` after `/npc attribute my_npc pose sitting`, my npc's pose is very strange
![изображение](https://github.com/FancyMcPlugins/FancyNpcs/assets/87126318/0b4c0def-9cc8-42bc-9716-b2ea7b36a10a)

I think you should add `/npc attribute my_npc sitting <true/false>` instead of `/npc attribute my_npc pose sitting`

**Comment by OliverSchlueter** [comment]
Which version of FancyNpcs do you use?

**Comment by envizar** [comment]
2.0.7

**Comment by OliverSchlueter** [comment]
Which server software and version do you use? I just tested with paper and folia 1.20.4 and it works fine

**Comment by envizar** [comment]
No such problem after updating to latest dev build
