### ISSUE TITLE
Send Random Messages NPC Command Not working.

### ISSUE THREAD

**Issue by sirjoehighton** [FancyMcPlugins/FancyNpcs#86]
Running this command does nothing at all even though its in the docs, Please fix as this is a feature i was hoping to use!

**Comment by sirjoealot** [comment]
Bug still occuring in version 2.0.8

**Comment by OliverSchlueter** [comment]
When sendRandomly is disabled, does it send all messages? Is there any error in console when toggling sendRandomly or interacting with the npc?
