### ISSUE TITLE
API's dependencies require their repositories to be defined

### ISSUE THREAD

**Issue by OakLoaf** [FancyMcPlugins/FancyNpcs#89]

**Comment by OliverSchlueter** [comment]
Steps to reproduce:
1. incude a dependency into your gradle project with `implementation` so it gets shaded into your plugin
2. publish your plugin to a maven-repo
3. use your plugin as dependency in another project

You will notice that you also need to include the repository of your plugin AND the repository of the dependency even though its shaded into the plugin.

If you have a possible solution for this problem or have questions feel free to comment here or dm me on discord (real_oliver).

**Comment by Grabsky** [comment]
@OliverSchlueter
You may want to see if changing `implementation` to `api` fixes that. I had a somewhat similar issue in the past and AFAIK this is how I got it resolved.

**Comment by OliverSchlueter** [comment]
Current solution: I'm mirroring the ChatColorHandler repo in FancyPlugins's repo

**Comment by OliverSchlueter** [comment]
If anyone has a better solution, let me know. I'll close this issue now tho
