### ISSUE TITLE
Suggest new features

### ISSUE THREAD

**Issue by LinAk900127** [FancyMcPlugins/FancyNpcs#90]
Can I hang the shopkeeper together and use fancy NPCs to modify the shopkeeper's skin?

**Comment by JonasDevDE** [comment]
Shouldn't be this a feature-request for the shopkeeper's plugin?

**Comment by OliverSchlueter** [comment]
Not planned.

You can use the "/shopkeeper remote" as serverCommand in your npc:
npc server_command (npc name) shopkeeper remote (shop id) {player}
shop id: the display name of the shopkeeper
