### ISSUE TITLE
Ability to disable saving

### ISSUE THREAD

**Issue by JonasDevDE** [FancyMcPlugins/FancyNpcs#92]
It would be cool if its possible to disable saving npcs in the config, some servers use cloud technology and want to manage their storage themselves.

**Comment by JonasDevDE** [comment]
> You can set Npc#setSaveToFile to false, then it won't save the npc.

Ah okay, but doesn't it also get saved by just creating it?

**Comment by OliverSchlueter** [comment]
No, it only gets saved in the autosave-scheduler and onDisable.
To make sure, you can set setSaveToFile to false before registering it to the NpcManager

**Comment by JonasDevDE** [comment]
> No, it only gets saved in the autosave-scheduler and onDisable.
> To make sure, you can set setSaveToFile to false before registering it to the NpcManager

Ah, okay. Thanks! 👍
