### ISSUE TITLE
NPCs with the PLAYER type do not exist on version 1.19.4 of PurPur

### ISSUE THREAD

**Issue by mochensky** [FancyMcPlugins/FancyNpcs#94]
An NPC with a PLAYER type does not exist in version 1.19.4 of PurPur. There are no errors in the console. The other types of entities work. I downloaded the plugin on spigotmc. I've been looking for a solution to this problem, but I haven't found anything. Can this be fixed?

Edited: I forgot to mention that the plugin version is 2.0.9

**Comment by OliverSchlueter** [comment]
Try to use the latest dev build (188) https://fancyplugins.de/FancyNpcs/download/

**Comment by mochensky** [comment]
Thank you, it really helped to solve this problem!
